# Generated by Django 5.0.1 on 2024-01-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_task_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='data_created',
            new_name='date_created',
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
