# Generated by Django 5.0.1 on 2024-01-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_rename_data_created_task_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='image/None/Noimg.jpg', upload_to='images/'),
        ),
    ]
